### ISSUE TITLE
Card Challenge: Nested For Loops

### ISSUE THREAD

**Issue by TheoBendixson** [MakeSchool-Tutorials/Getting-Started-With-Swift-2017#14]
While completing the card challenge, I realized that it was necessary to create a nested for loop in order to generate all of the possible permutations of cards in a deck.

I doubt this would be so obvious to a new student. The arrays module only covers one-dimensional arrays, and the control flow module makes no mention of nested loops.

Proposed Solutions:
1. Create a module explaining collection type nesting. Ideally this would go after the control flow module so we could explain how to use nested loops to iterate over the contents of multidimensional collections.

2. Give a hint just before the "Create a Deck" challenge question. Show how you might iterate over all possible ranks and suits to generate a deck with all possible cards.

**Comment by dionlarson** [comment]
Going to leave this pretty vague as majority of students will have nested loop experience in another language.
