### ISSUE TITLE
Control Flow Challenge Question #5

### ISSUE THREAD

**Issue by TheoBendixson** [MakeSchool-Tutorials/Getting-Started-With-Swift-2017#9]
This one isn't really an issue so much as an idea.

It would be really cool if we could move this question from being "Imagine you are making a game" to actually using a SKScene and SpriteKit to make a simple game. So far as I understand, such a thing is possible in Swift Playgrounds.

**Comment by dionlarson** [comment]
Definitely possible but beyond the level of involvement we want in these playgrounds. Adding views like that leads to a bit of instability that just does not add enough to make it worthwhile in this case.

Check out the explorer playgrounds, they have some great visuals!
